language: cpp

sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      compiler: g++
      addons:
        apt:
          sources:
            - boost-latest
            - travis-ci/sqlite3
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - g++-5
            - libboost1.58-all-dev
            - libsqlite3-dev
      env:
        - CMAKE_BUILD_TYPE=Debug
        - CMAKE_C_COMPILER=gcc-5
        - CMAKE_CXX_COMPILER=g++-5


before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update;
      brew install llvm37 sqlite3;
      brew outdated boost || brew upgrade boost;
    fi

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER} -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER} ..

script:
  - make
  - make test
