sudo:
    - true

language:
    - cpp

addons:
    apt:
        sources:
            - boost-latest
            - ubuntu-toolchain-r-test
        packages:
            - g++-5

matrix:
    include:
        - os: linux
          compiler: gcc
          env: LINK=dynamic
          apt:
        - os: linux
          compiler: gcc
          env: LINK=static
          apt:
            packages:
                - lcov
    fast_finish:
        - true

before_install:

    # Set aliases for readability.
    - if [[ $CC             == gcc     ]]; then GCC=true; fi
    - if [[ $CC             == clang   ]]; then CLANG=true; fi
    - if [[ $LINK           == static  ]]; then STATIC=true; fi
    - if [[ $LINK           == dynamic ]]; then DYNAMIC=true; fi
    - if [[ $TRAVIS_OS_NAME == osx     ]]; then OSX=true; fi
    - if [[ $TRAVIS_OS_NAME == linux   ]]; then LINUX=true; fi

install:

    # Export CC/CXX to control gcc version.
    - if [[ $GCC                         ]]; then export CC=gcc-5; export CXX=g++-5;  fi


script:
    # Download and build libbitcoin-network and all dependencies.
    - if [[ $LINUX && $GCC   && $STATIC  ]]; then CC=$CC CXX=$CXX sudo ./install.sh --build-boost --build-dir=my-build --prefix=$TRAVIS_BUILD_DIR/my-prefix ; fi
    #- if [[ $LINUX && $GCC   && $DYNAMIC ]]; then CC=$CC CXX=$CXX sudo ./install.sh --disable-static --build-boost --prefix=$TRAVIS_BUILD_DIR/my-prefix CFLAGS='-Os -s' CXXFLAGS='-Os -s'; fi


after_success:

    # Install coveralls and current lcov.
    - if [[ $LINUX && $GCC   && $STATIC  ]]; then gem install coveralls-lcov; fi

    # Capture coverage info, filter out system and test code, and debug before upload.
    - if [[ $LINUX && $GCC   && $STATIC  ]]; then lcov --directory . --capture --output-file coverage.info; fi
    - if [[ $LINUX && $GCC   && $STATIC  ]]; then lcov --remove coverage.info "/usr/*" "$TRAVIS_BUILD_DIR/my-prefix/*" "my-build/*" "test/*" --output-file coverage.info; fi
    - if [[ $LINUX && $GCC   && $STATIC  ]]; then lcov --list coverage.info; fi

    # Upload coverage info to coveralls service (--repo-token <private coveralls repo token>).
    - if [[ $LINUX && $GCC   && $STATIC  ]]; then coveralls-lcov coverage.info; fi
